dubbo:
  application:
    name: service-consumer02
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://127.0.0.1:8848
server:
  port: 8092
spring:
  application:
    name: service-consumer02
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848