dubbo:
  application:
    name: service-provider01
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://127.0.0.1:8848,127.0.0.1:8849,127.0.0.1:8850
server:
  port: 8081
spring:
  application:
    name: service-provider01